# Use the official Node.js image from the Docker Hub as a base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install
# If you are building your code for production, use the following line instead:
# RUN npm ci --only=production

# Copy the rest of your application code
COPY . .

# Command to run your application
CMD ["node", "index.js"]
