apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ninja-app
  labels:
    app: deploy-ninja-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-ninja-app
  template:
    metadata:
      labels:
        app: deploy-ninja-app
    spec:
      containers:
      - name: deploy-ninja-app
        image: emzm17/deploy-ninja-repo:latest
        ports:
        - containerPort: 8080
