name: CD Pipeline

on:
  push:
    branches:
      - new-prod-1
  pull_request:
    branches:
      - new-prod-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Server and Check for Updates
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Navigate to application directory
          cd /${{ secrets.SERVER_USERNAME }}/app
          
          # Fetch the latest changes from the remote
          git fetch

          # Get the current branch name
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Get the latest commit hash on the current branch
          LOCAL_COMMIT=$(git rev-parse $CURRENT_BRANCH)

          # Get the latest commit hash from the remote repository
          REMOTE_COMMIT=$(git rev-parse origin/$CURRENT_BRANCH)

          # Compare the local and remote commit hashes
          if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
            echo "New commits found. Proceeding with deployment..."
          else
            echo "Already up-to-date. No new commits found."
            exit 0
          fi
          EOF

      - name: SSH into Server and Deploy
        if: success() # Only run this step if the previous step was successful
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Navigate to application directory
          cd /${{ secrets.SERVER_USERNAME }}/app
          
          # Stop the existing application
          echo "Stopping the existing application..."
          ./root/app/node_script.sh # script to kill all running node processes

          # Pull the latest changes from the repository
          echo "Pulling latest changes..."
          git pull origin new-prod-1

          # Start the new application
          echo "Starting the new application..."
          npm run start:prod
          EOF
