name: CD Pipeline

on:
  pull_request:
    branches:
      - new-prod-1
  push:
    branches:
      - new-prod-1    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key
      - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa <<< "${{ secrets.SSH_PASSPHRASE }}"
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      shell: bash
      - name: Deploy to server
      run: |
        ssh user@${{ secrets.HOST }} "whoami"