name: CD Pipeline

on:
  pull_request:
    branches:
      - new-prod-1
  push:
    branches:
      - new-prod-1    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key
      - name: SSH into Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: whoami
          host: ${{ secrets.SERVER_HOST }}
          username: root
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SERVER_PRIVATE_KEY}}

