name: Build and Push Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - new-prod-1
  push:
    branches:
      - new-prod-1

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          cd build-server
          docker build \
            -f Dockerfile \
            --build-arg ENDPOINT=${{ secrets.ENDPOINT }} \
            --build-arg accessKeyId=${{ secrets.accessKeyId }} \
            --build-arg secretAccessKey=${{ secrets.secretAccessKey }} \
            --build-arg bucket=${{ secrets.bucket }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest .
      
      - name: Build Deployment Image
        run: |
          cd build-server 
          docker build \
            -f Dockerfile.prod \
            --build-arg REDIS_URL=${{ secrets.REDIS_URL }} \
            --build-arg REDIS_QUEUE=${{ secrets.REDIS_QUEUE }} \
            --build-arg DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE2 }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE1 }}:latest .
      
      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE1 }}:latest
      
      - name: Verify push status
        run: echo "Push image to Docker Hub"