name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - new-prod-1

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          cd build-server
          docker build \
            -f Dockerfile \
            --build-arg ENDPOINT=${{ secrets.ENDPOINT }} \
            --build-arg accessKeyId=${{ secrets.accessKeyId }} \
            --build-arg secretAccessKey=${{ secrets.secretAccessKey }} \
            --build-arg bucket=${{ secrets.bucket }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest  .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
      
      - name: Verify push status
        run: |
            echo "Push image to Docker Hub"
